In [1]:
import os
import pandas as pd

data_path = "data/credit_card_transactions.csv"
current_path = os.getcwd()

In [3]:
df = pd.read_csv(os.path.join(current_path, '..', data_path)).iloc[:,1:]
df

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,merch_zipcode
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,28705.0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,NaN
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,83236.0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,NaN
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,22844.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,Hatch,...,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0,NaN
1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,Tuscarora,...,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0,22630.0
1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,High Rolls Mountain Park,...,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0,88351.0
1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,Manderson,...,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0,69367.0
1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,Sula,...,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0,59870.0

In [4]:
# check if got null data
df.isnull().sum()
# null value only found for merchant zipcode

trans_date_trans_time         0
cc_num                        0
merchant                      0
category                      0
amt                           0
first                         0
last                          0
gender                        0
street                        0
city                          0
state                         0
zip                           0
lat                           0
long                          0
city_pop                      0
job                           0
dob                           0
trans_num                     0
unix_time                     0
merch_lat                     0
merch_long                    0
is_fraud                      0
merch_zipcode            195973
dtype: int64

In [15]:
# check accuracy for category / seems ok
df.groupby(["category"]).cc_num.count()

category
entertainment      94014
food_dining        91461
gas_transport     131659
grocery_net        45452
grocery_pos       123638
health_fitness     85879
home              123115
kids_pets         113035
misc_net           63287
misc_pos           79655
personal_care      90758
shopping_net       97543
shopping_pos      116672
travel             40507
Name: cc_num, dtype: int64

In [20]:
# check fraud percentage
df.groupby("is_fraud").cc_num.count()

is_fraud
0    1289169
1       7506
Name: cc_num, dtype: int64

In [23]:
print("this is about ",(7506/1289169)*100,"% of fraud records")

this is about  0.5822355331224999 % of fraud records

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  object
 1   cc_num                 1296675 non-null  int64
 2   merchant               1296675 non-null  object
 3   category               1296675 non-null  object
 4   amt                    1296675 non-null  float64
 5   first                  1296675 non-null  object
 6   last                   1296675 non-null  object
 7   gender                 1296675 non-null  object
 8   street                 1296675 non-null  object
 9   city                   1296675 non-null  object
 10  state                  1296675 non-null  object
 11  zip                    1296675 non-null  int64
 12  lat                    1296675 non-null  float64
 13  long                   1296675 non-null  float64
 14  city_pop               1296675 non-null  int64
 15  job                    1296675 non-null  object
 16  dob                    1296675 non-null  object
 17  trans_num              1296675 non-null  object
 18  unix_time              1296675 non-null  int64
 19  merch_lat              1296675 non-null  float64
 20  merch_long             1296675 non-null  float64
 21  is_fraud               1296675 non-null  int64
 22  merch_zipcode          1100702 non-null  float64
dtypes: float64(6), int64(5), object(12)
memory usage: 227.5+ MB

In [13]:
df['trans_datetime'] = pd.to_datetime(df.trans_date_trans_time)
df.groupby(pd.Grouper(key="trans_datetime", freq='ME')).amt.count()
# data includes from 2019 Jan to 2020 Jun transaction, 18 months,

trans_datetime
2019-01-31     52525
2019-02-28     49866
2019-03-31     70939
2019-04-30     68078
2019-05-31     72532
2019-06-30     86064
2019-07-31     86596
2019-08-31     87359
2019-09-30     70652
2019-10-31     68758
2019-11-30     70421
2019-12-31    141060
2020-01-31     52202
2020-02-29     47791
2020-03-31     72850
2020-04-30     66892
2020-05-31     74343
2020-06-30     57747
Freq: ME, Name: amt, dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 24 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   trans_date_trans_time  1296675 non-null  object
 1   cc_num                 1296675 non-null  int64
 2   merchant               1296675 non-null  object
 3   category               1296675 non-null  object
 4   amt                    1296675 non-null  float64
 5   first                  1296675 non-null  object
 6   last                   1296675 non-null  object
 7   gender                 1296675 non-null  object
 8   street                 1296675 non-null  object
 9   city                   1296675 non-null  object
 10  state                  1296675 non-null  object
 11  zip                    1296675 non-null  int64
 12  lat                    1296675 non-null  float64
 13  long                   1296675 non-null  float64
 14  city_pop               1296675 non-null  int64
 15  job                    1296675 non-null  object
 16  dob                    1296675 non-null  object
 17  trans_num              1296675 non-null  object
 18  unix_time              1296675 non-null  int64
 19  merch_lat              1296675 non-null  float64
 20  merch_long             1296675 non-null  float64
 21  is_fraud               1296675 non-null  int64
 22  merch_zipcode          1100702 non-null  float64
 23  trans_datetime         1296675 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(6), int64(5), object(12)
memory usage: 237.4+ MB

In [36]:
len(df.cc_num.unique())

983

In [38]:
len(df.trans_num.unique())
# this is transaction_id

1296675

In [40]:
df['full_name']=df['first'] + " " + df['last']

In [42]:
len(df.full_name.unique())

973

In [52]:
# below shows the number of transactions each user made.. some users made so many transactions ?????
sorted(df.groupby(['full_name','cc_num']).trans_num.count())

[7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 15,
 15,
 15,
 19,
 471,
 475,
 480,
 481,
 483,
 485,
 485,
 490,
 490,
 490,
 491,
 491,
 492,
 492,
 492,
 493,
 493,
 494,
 495,
 495,
 496,
 496,
 496,
 497,
 498,
 499,
 499,
 499,
 500,
 501,
 501,
 501,
 501,
 501,
 501,
 501,
 502,
 502,
 502,
 502,
 503,
 503,
 503,
 503,
 503,
 503,
 503,
 503,
 504,
 504,
 504,
 504,
 504,
 504,
 504,
 505,
 505,
 505,
 506,
 506,
 506,
 506,
 506,
 506,
 507,
 507,
 507,
 508,
 508,
 508,
 508,
 509,
 509,
 509,
 509,
 509,
 509,
 509,
 510,
 510,
 510,
 510,
 510,
 510,
 510,
 510,
 511,
 511,
 511,
 511,
 511,
 512,
 512,
 512,
 513,
 513,
 513,
 513,
 514,
 514,
 514,
 514,
 514,
 515,
 515,
 515,
 515,
 515,
 516,
 516,
 516,
 516,
 516,
 516,
 516,
 516,
 516,
 517,
 517,
 517,
 518,
 518,
 518,
 518,
 518,
 518,
 518,
 518,
 518,
 519,
 519,
 519,
 519,
 519,
 519,
 519,
 519,
 519,
 519,
 519,
 519,
 520,
 520,
 520,
 520,
 520,
 520,
 521,
 521,
 521,
 521,
 521,
 521,
 521,
 521,
 521,
 521,
 521,
 522,
 522,
 522,
 523,
 523,
 523,
 524,
 524,
 524,
 524,
 524,
 524,
 525,
 525,
 525,
 525,
 525,
 526,
 526,
 527,
 527,
 528,
 528,
 528,
 528,
 529,
 529,
 529,
 529,
 529,
 529,
 529,
 530,
 530,
 530,
 531,
 532,
 532,
 532,
 533,
 533,
 533,
 534,
 534,
 535,
 535,
 536,
 536,
 536,
 537,
 537,
 537,
 538,
 538,
 538,
 540,
 540,
 542,
 544,
 545,
 550,
 552,
 554,
 972,
 985,
 989,
 990,
 993,
 994,
 995,
 997,
 998,
 998,
 999,
 1000,
 1001,
 1001,
 1001,
 1002,
 1002,
 1002,
 1003,
 1003,
 1004,
 1005,
 1005,
 1006,
 1006,
 1007,
 1007,
 1007,
 1008,
 1008,
 1008,
 1008,
 1009,
 1009,
 1009,
 1009,
 1009,
 1010,
 1010,
 1010,
 1011,
 1012,
 1012,
 1012,
 1013,
 1013,
 1014,
 1014,
 1014,
 1014,
 1014,
 1014,
 1015,
 1015,
 1016,
 1016,
 1016,
 1017,
 1018,
 1019,
 1019,
 1019,
 1020,
 1020,
 1021,
 1021,
 1021,
 1021,
 1021,
 1022,
 1022,
 1022,
 1023,
 1023,
 1023,
 1023,
 1023,
 1023,
 1024,
 1024,
 1024,
 1024,
 1024,
 1025,
 1025,
 1025,
 1025,
 1026,
 1026,
 1026,
 1026,
 1026,
 1026,
 1026,
 1026,
 1026,
 1027,
 1027,
 1027,
 1027,
 1027,
 1027,
 1027,
 1028,
 1028,
 1028,
 1028,
 1028,
 1029,
 1029,
 1029,
 1029,
 1029,
 1029,
 1030,
 1030,
 1031,
 1031,
 1031,
 1031,
 1031,
 1032,
 1032,
 1033,
 1033,
 1033,
 1033,
 1033,
 1033,
 1034,
 1034,
 1034,
 1034,
 1035,
 1035,
 1035,
 1036,
 1036,
 1036,
 1036,
 1037,
 1038,
 1038,
 1038,
 1038,
 1039,
 1039,
 1039,
 1039,
 1039,
 1039,
 1039,
 1039,
 1040,
 1040,
 1040,
 1040,
 1041,
 1041,
 1041,
 1041,
 1042,
 1042,
 1043,
 1043,
 1043,
 1044,
 1044,
 1045,
 1045,
 1045,
 1045,
 1045,
 1045,
 1046,
 1046,
 1046,
 1046,
 1047,
 1047,
 1047,
 1047,
 1047,
 1048,
 1049,
 1049,
 1049,
 1050,
 1050,
 1051,
 1052,
 1052,
 1052,
 1054,
 1054,
 1054,
 1055,
 1055,
 1056,
 1058,
 1058,
 1060,
 1069,
 1070,
 1466,
 1471,
 1476,
 1491,
 1494,
 1496,
 1496,
 1497,
 1500,
 1503,
 1504,
 1505,
 1505,
 1506,
 1507,
 1509,
 1510,
 1510,
 1511,
 1512,
 1512,
 1512,
 1512,
 1512,
 1513,
 1513,
 1513,
 1513,
 1514,
 1514,
 1514,
 1514,
 1516,
 1517,
 1517,
 1517,
 1517,
 1518,
 1518,
 1519,
 1519,
 1519,
 1519,
 1519,
 1520,
 1520,
 1521,
 1522,
 1522,
 1522,
 1523,
 1523,
 1523,
 1523,
 1523,
 1524,
 1524,
 1525,
 1525,
 1525,
 1525,
 1525,
 1525,
 1526,
 1526,
 1526,
 1527,
 1527,
 1527,
 1527,
 1527,
 1527,
 1527,
 1528,
 1528,
 1528,
 1528,
 1528,
 1529,
 1529,
 1529,
 1530,
 1530,
 1531,
 1531,
 1531,
 1532,
 1533,
 1533,
 1534,
 1534,
 1535,
 1535,
 1535,
 1535,
 1535,
 1535,
 1535,
 1535,
 1535,
 1535,
 1537,
 1537,
 1537,
 1538,
 1538,
 1538,
 1538,
 1538,
 1538,
 1538,
 1539,
 1539,
 1539,
 1540,
 1540,
 1540,
 1541,
 1542,
 1542,
 1542,
 1542,
 1542,
 1543,
 1543,
 1543,
 1543,
 1543,
 1544,
 1544,
 1544,
 1544,
 1545,
 1546,
 1546,
 1547,
 1547,
 1547,
 1547,
 1548,
 1548,
 1548,
 1548,
 1549,
 1549,
 1549,
 1549,
 1549,
 1550,
 1550,
 1551,
 1551,
 1551,
 1551,
 1551,
 1552,
 1553,
 1553,
 1553,
 1554,
 1554,
 1554,
 1555,
 1555,
 1555,
 1556,
 1556,
 1556,
 1557,
 1557,
 1557,
 1557,
 1558,
 1558,
 1558,
 1558,
 1559,
 1559,
 1559,
 1559,
 1560,
 1560,
 1560,
 1561,
 1562,
 1563,
 1563,
 1563,
 1564,
 1565,
 1565,
 1566,
 1566,
 1567,
 1568,
 1569,
 1569,
 1570,
 1571,
 1572,
 1574,
 1577,
 1578,
 1581,
 1587,
 1588,
 1597,
 1959,
 1979,
 1996,
 2000,
 2001,
 2002,
 2002,
 2003,
 2003,
 2009,
 2013,
 2013,
 2014,
 2015,
 2015,
 2016,
 2016,
 2017,
 2018,
 2019,
 2021,
 2021,
 2023,
 2023,
 2024,
 2024,
 2024,
 2024,
 2024,
 2025,
 2025,
 2026,
 2027,
 2028,
 2028,
 2028,
 2029,
 2030,
 2030,
 2032,
 2032,
 2033,
 2033,
 2034,
 2034,
 2034,
 2035,
 2035,
 2035,
 2035,
 2036,
 2036,
 2037,
 2037,
 2037,
 2037,
 2038,
 2038,
 2038,
 2038,
 2039,
 2041,
 2041,
 2042,
 2042,
 2042,
 2043,
 2043,
 2044,
 2045,
 2045,
 2046,
 2046,
 2047,
 2047,
 2047,
 2048,
 2048,
 2048,
 2049,
 2049,
 2049,
 2049,
 2049,
 2050,
 2050,
 2050,
 2050,
 2051,
 2051,
 2051,
 2052,
 2052,
 2052,
 2053,
 2054,
 2054,
 2054,
 2056,
 2056,
 2057,
 2058,
 2058,
 2058,
 2059,
 2059,
 2060,
 2060,
 2062,
 2062,
 2063,
 2063,
 2064,
 2064,
 2065,
 2066,
 2068,
 2068,
 2069,
 2069,
 2069,
 2070,
 2070,
 2071,
 2073,
 2073,
 2074,
 2074,
 2075,
 2075,
 2080,
 2080,
 2080,
 2080,
 2082,
 2083,
 2087,
 2087,
 2087,
 2088,
 2089,
 2090,
 2090,
 2091,
 2092,
 2093,
 2097,
 2101,
 2102,
 2106,
 2107,
 2109,
 2456,
 2458,
 2498,
 2503,
 2519,
 2521,
 2523,
 2524,
 2524,
 2525,
 2525,
 2527,
 2530,
 2530,
 2534,
 2539,
 2540,
 2540,
 2541,
 2547,
 2548,
 2551,
 2552,
 2553,
 2553,
 2554,
 2554,
 2555,
 2555,
 2556,
 2558,
 2558,
 2559,
 2561,
 2562,
 2562,
 2562,
 2562,
 2564,
 2564,
 2564,
 2564,
 2565,
 2566,
 2566,
 2568,
 2570,
 2572,
 2572,
 2572,
 2573,
 2574,
 2576,
 2577,
 2578,
 2578,
 2582,
 2584,
 2585,
 2585,
 2587,
 2587,
 2588,
 2590,
 2591,
 2597,
 2599,
 2602,
 2603,
 2611,
 2619,
 2915,
 2918,
 2918,
 2922,
 2949,
 2949,
 2973,
 3006,
 3011,
 3023,
 3026,
 3026,
 3027,
 3027,
 3030,
 3032,
 3034,
 3038,
 3039,
 3040,
 3045,
 3046,
 3051,
 3054,
 3055,
 3056,
 3061,
 3064,
 3071,
 3072,
 3074,
 3074,
 3077,
 3080,
 3081,
 3082,
 3083,
 3087,
 3088,
 3090,
 3090,
 3095,
 3099,
 3101,
 3106,
 3107,
 3110,
 3112,
 3113,
 3117,
 3119,
 3123,
 3123]

In [17]:
df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'merch_zipcode', 'trans_datetime'],
      dtype='object')

In [20]:
len(df.merchant.unique())

693

In [33]:
df['age'] = ((df.trans_datetime - pd.to_datetime(df.dob)).dt.days/365).round()

In [53]:
categorical_cols = [ 'merchant','category','gender','city','state', 'job','full_name']
numerical_cols  = ['amt','age']